import type { SmokeScenario, SmokeSuite } from './result.js';

const script = (name: string): string[] => ['tsx', `devtools/repo-cli/src/scripts/${name}`];

export const smokeSuites: SmokeSuite[] = ['core', 'agent', 'governance', 'ui', 'real'];

export const smokeCatalog: SmokeScenario[] = [
  {
    id: 'db-registry',
    suite: 'core',
    description: 'DB-backed registry route preview and mock workflow starter development path.',
    mode: 'ci',
    timeoutMs: 60_000,
    command: script('smoke-db-registry.ts'),
  },
  {
    id: 'temporal-db',
    suite: 'core',
    description: 'Temporal workflow with DB-backed registry, audit, tool calls, and human approval.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-temporal-db-e2e.ts'),
  },
  {
    id: 'control-plane-api',
    suite: 'core',
    description: 'Control-plane API registry and release smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-control-plane-api-e2e.ts'),
    env: { EVALUATION_GATE_MODE: 'advisory' },
  },
  {
    id: 'semantic-router',
    suite: 'core',
    description: 'Semantic route embedding and recall smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-semantic-router-e2e.ts'),
  },
  {
    id: 'http-readonly-tool',
    suite: 'core',
    description: 'HTTP readonly tool adapter policy and audit smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-http-readonly-tool-e2e.ts'),
  },
  {
    id: 'pi-readonly',
    suite: 'agent',
    description: 'Pi model-gateway readonly tool path through mock-server.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-pi-e2e.ts'),
    env: { PI_SMOKE_SCENARIO: 'readonly_tool', PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
  },
  {
    id: 'pi-l3',
    suite: 'agent',
    description: 'Pi model-gateway L3 preview/approval/commit path through mock-server.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-pi-e2e.ts'),
    env: { PI_SMOKE_SCENARIO: 'l3_tool', PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
  },
  {
    id: 'pi-user-input',
    suite: 'agent',
    description: 'Pi model-gateway user input deferred tool path through mock-server.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-pi-e2e.ts'),
    env: { PI_SMOKE_SCENARIO: 'user_input', PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
  },
  {
    id: 'pi-handoff',
    suite: 'agent',
    description: 'Pi model-gateway workflow handoff deferred tool path through mock-server.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-pi-e2e.ts'),
    env: { PI_SMOKE_SCENARIO: 'handoff', PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
  },
  {
    id: 'pi-model-gateway',
    suite: 'agent',
    description: 'Pi model-gateway direct smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-pi-e2e.ts'),
    env: { PI_SMOKE_SCENARIO: 'model_gateway', PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
  },
  {
    id: 'pi-model-gateway-retry',
    suite: 'agent',
    description: 'Pi model-gateway retry path for transient 429 through mock-server.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-pi-e2e.ts'),
    env: { PI_SMOKE_SCENARIO: 'rate_limit_then_success', PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
  },
  {
    id: 'pi-restart-resume',
    suite: 'agent',
    description: 'Pi restart/resume scenario through model gateway mock-server.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-pi-e2e.ts'),
    env: { PI_SMOKE_SCENARIO: 'restart_resume', PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
  },
  {
    id: 'worker-crash-resume',
    suite: 'agent',
    description: 'Worker crash and durable resume smoke.',
    mode: 'ci',
    timeoutMs: 240_000,
    command: script('smoke-pi-worker-crash-resume-e2e.ts'),
    env: { PI_SMOKE_MODE: 'model_gateway', MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions' },
    artifacts: ['artifacts/pi-worker-crash-resume/result.json'],
  },
  {
    id: 'tenant-policy',
    suite: 'governance',
    description: 'Tenant runtime policy smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-tenant-policy-e2e.ts'),
    env: { TENANT_POLICY_SMOKE_SCENARIO: 'policy' },
  },
  {
    id: 'tenant-snapshot',
    suite: 'governance',
    description: 'Tenant policy snapshot immutability smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-tenant-policy-e2e.ts'),
    env: { TENANT_POLICY_SMOKE_SCENARIO: 'snapshot' },
  },
  {
    id: 'tenant-concurrency',
    suite: 'governance',
    description: 'Tenant admission concurrency smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-tenant-policy-e2e.ts'),
    env: { TENANT_POLICY_SMOKE_SCENARIO: 'concurrency' },
  },
  {
    id: 'tenant-deep-chain',
    suite: 'governance',
    description: 'Flow to agent policy lineage smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-tenant-deep-chain-e2e.ts'),
    env: { TENANT_DEEP_SMOKE_SCENARIO: 'flow_agent' },
  },
  {
    id: 'tenant-handoff-lineage',
    suite: 'governance',
    description: 'Tenant policy lineage through workflow handoff.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-tenant-deep-chain-e2e.ts'),
    env: { TENANT_DEEP_SMOKE_SCENARIO: 'handoff_lineage' },
  },
  {
    id: 'tenant-policy-crash-snapshot',
    suite: 'governance',
    description: 'Tenant snapshot locking during worker crash/resume.',
    mode: 'ci',
    timeoutMs: 240_000,
    command: script('smoke-tenant-deep-chain-e2e.ts'),
    env: { TENANT_DEEP_SMOKE_SCENARIO: 'policy_crash_snapshot' },
  },
  {
    id: 'tenant-admission-reconcile',
    suite: 'governance',
    description: 'Tenant admission reconciliation smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-tenant-deep-chain-e2e.ts'),
    env: { TENANT_DEEP_SMOKE_SCENARIO: 'admission_reconcile' },
  },
  {
    id: 'evaluation-framework',
    suite: 'governance',
    description: 'Evaluation framework backend smoke.',
    mode: 'ci',
    timeoutMs: 240_000,
    command: script('smoke-evaluation-backend-e2e.ts'),
    env: { EVALUATION_GATE_MODE: 'required', EVALUATION_SMOKE_SCENARIO: 'framework' },
    artifacts: ['artifacts/evaluation-backend-e2e/framework.json'],
  },
  {
    id: 'evaluation-gates',
    suite: 'governance',
    description: 'Focused evaluation gate checks.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-evaluation-gates.ts'),
  },
  {
    id: 'evaluation-regression',
    suite: 'governance',
    description: 'Evaluation regression gate smoke.',
    mode: 'ci',
    timeoutMs: 240_000,
    command: script('smoke-evaluation-backend-e2e.ts'),
    env: { EVALUATION_GATE_MODE: 'required', EVALUATION_SMOKE_SCENARIO: 'regression' },
  },
  {
    id: 'evaluation-publish-gate',
    suite: 'governance',
    description: 'Evaluation publish gate smoke.',
    mode: 'ci',
    timeoutMs: 240_000,
    command: script('smoke-evaluation-backend-e2e.ts'),
    env: { EVALUATION_GATE_MODE: 'required', EVALUATION_SMOKE_SCENARIO: 'publish_gate' },
  },
  {
    id: 'model-catalog',
    suite: 'governance',
    description: 'Model catalog multi-gateway smoke.',
    mode: 'ci',
    timeoutMs: 180_000,
    command: script('smoke-model-catalog-multi-gateway-e2e.ts'),
  },
  {
    id: 'replay',
    suite: 'governance',
    description: 'Temporal replay fixture test.',
    mode: 'ci',
    timeoutMs: 120_000,
    command: ['vitest', 'run', 'tests/temporal-replay', '--config', 'vitest.root.config.ts'],
  },
  {
    id: 'control-plane-ui',
    suite: 'ui',
    description: 'Control-plane UI smoke.',
    mode: 'ci',
    timeoutMs: 240_000,
    command: script('smoke-control-plane-ui-e2e.ts'),
    artifacts: ['artifacts/control-plane-ui-e2e'],
  },
  {
    id: 'evaluation-ui',
    suite: 'ui',
    description: 'Evaluation UI smoke.',
    mode: 'ci',
    timeoutMs: 240_000,
    command: script('smoke-evaluation-ui-e2e.ts'),
    artifacts: ['artifacts/evaluation-ui-e2e'],
  },
  {
    id: 'ollama-runtime',
    suite: 'real',
    description: 'Manual/self-hosted containerized Ollama runtime smoke.',
    mode: 'real',
    timeoutMs: 600_000,
    command: script('smoke-ollama-containerized-e2e.ts'),
  },
  {
    id: 'ollama-runtime-final',
    suite: 'real',
    description: 'Manual/self-hosted Ollama final-answer runtime path.',
    mode: 'real',
    timeoutMs: 300_000,
    command: script('smoke-pi-e2e.ts'),
    env: {
      PI_SMOKE_SCENARIO: 'model_gateway_final',
      PI_SMOKE_MODE: 'model_gateway',
      MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions',
      MODEL_GATEWAY_PROVIDER: 'local-ollama',
      MODEL_GATEWAY_MODEL: 'qwen2.5:7b-instruct-q4_K_M',
    },
  },
  {
    id: 'ollama-runtime-readonly',
    suite: 'real',
    description: 'Manual/self-hosted Ollama readonly tool runtime path.',
    mode: 'real',
    timeoutMs: 300_000,
    command: script('smoke-pi-e2e.ts'),
    env: {
      PI_SMOKE_SCENARIO: 'readonly_tool',
      PI_SMOKE_MODE: 'model_gateway',
      MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions',
      MODEL_GATEWAY_PROVIDER: 'local-ollama',
      MODEL_GATEWAY_MODEL: 'qwen2.5:7b-instruct-q4_K_M',
    },
  },
  {
    id: 'ollama-runtime-l3',
    suite: 'real',
    description: 'Manual/self-hosted Ollama L3 tool runtime path.',
    mode: 'real',
    timeoutMs: 300_000,
    command: script('smoke-pi-e2e.ts'),
    env: {
      PI_SMOKE_SCENARIO: 'l3_tool',
      PI_SMOKE_MODE: 'model_gateway',
      MODEL_GATEWAY_PROTOCOL: 'openai_chat_completions',
      MODEL_GATEWAY_PROVIDER: 'local-ollama',
      MODEL_GATEWAY_MODEL: 'qwen2.5:7b-instruct-q4_K_M',
    },
  },
  {
    id: 'ollama-evaluation',
    suite: 'real',
    description: 'Manual/self-hosted Ollama evaluation smoke.',
    mode: 'real',
    timeoutMs: 600_000,
    command: script('smoke-evaluation-ollama-e2e.ts'),
  },
  {
    id: 'live-model-provider',
    suite: 'real',
    description: 'Manual live model provider smoke.',
    mode: 'real',
    timeoutMs: 300_000,
    command: script('smoke-model-gateway-live.ts'),
  },
  {
    id: 'live-model-provider-final',
    suite: 'real',
    description: 'Manual live model provider final-answer path.',
    mode: 'real',
    timeoutMs: 300_000,
    command: script('smoke-model-gateway-live.ts'),
    env: { LIVE_MODEL_GATEWAY_SCENARIO: 'final' },
  },
  {
    id: 'live-model-provider-readonly',
    suite: 'real',
    description: 'Manual live model provider readonly tool path.',
    mode: 'real',
    timeoutMs: 300_000,
    command: script('smoke-model-gateway-live.ts'),
    env: { LIVE_MODEL_GATEWAY_SCENARIO: 'readonly' },
  },
  {
    id: 'live-model-provider-l3',
    suite: 'real',
    description: 'Manual live model provider L3 tool path.',
    mode: 'real',
    timeoutMs: 300_000,
    command: script('smoke-model-gateway-live.ts'),
    env: { LIVE_MODEL_GATEWAY_SCENARIO: 'l3' },
  },
];

export function scenarioById(id: string): SmokeScenario | undefined {
  return smokeCatalog.find((scenario) => scenario.id === id);
}

export function scenariosBySuite(suite: SmokeSuite): SmokeScenario[] {
  return smokeCatalog.filter((scenario) => scenario.suite === suite);
}

export function isSmokeSuite(value: string): value is SmokeSuite {
  return smokeSuites.includes(value as SmokeSuite);
}
